#!/bin/sh

printf "Updates in the AUR:\n"
cower -u

printf "\nUpdates for runical-bin:\n"
aurcheck -q runical-bin

printf "\nUpdates for runical:\n"
aurcheck -q runical

printf "\nUpdates for runical-vcs:\n"
aurcheck -q runical-vcs

printf "\nUpdates in repositories:\n"
checkupdates

printf "\n"
