#!/bin/sh

printf "Updates in the AUR:\n"
cower -u

printf "\nUpdates for runical-bin:\n"
aurcheck -d runical-bin

printf "\nUpdates for runical:\n"
aurcheck -d runical

printf "\nUpdates for runical-vcs:\n"
aurcheck -d runical-vcs

printf "\nUpdates in repositories:\n"
checkupdates

printf "\n"
